server:
  port: 8080

spring:
  application:
    name: Employee-Tracking-System

  datasource:
    url: jdbc:postgresql://ep-lucky-morning-a8672f4i-pooler.eastus2.azure.neon.tech:5432/emp-trk?sslmode=require
    username: emp-trk_owner
    password: npg_cVT5Fio3JxAS

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  main:
    allow-circular-references: true

